# Generated by Django 5.1.2 on 2024-10-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_delete_contactsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
