# Generated by Django 5.1.2 on 2024-11-07 16:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('html_subtitle', models.TextField(blank=True, help_text='This can include Raw HTML. Be careful!', max_length=2000)),
                ('body', wagtail.fields.StreamField([('content', 0), ('image', 1), ('video_block', 6), ('quote', 7), ('twitter_block', 9), ('code_block', 12), ('result_block', 13)], block_lookup={0: ('utils.models.UtilsCustomRichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('video_url', 3), ('video_file', 4), ('poster_image', 5)]], {'template': 'blocks/video_block.html'}), 7: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8)]], {'template': 'blocks/twitter_block.html'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('shell', 'Shell')], 'label': 'Language code'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Source code'}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {}), 13: ('utils.models.UtilsResultBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
