# Generated by Django 5.1.2 on 2024-10-29 09:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 0), ('image', 1), ('video_block', 6), ('quote', 7), ('twitter_block', 9), ('code_block', 12), ('result_block', 13)], block_lookup={0: ('utils.models.UtilsCustomRichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('video_url', 3), ('video_file', 4), ('poster_image', 5)]], {'template': 'blocks/video_block.html'}), 7: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8)]], {'template': 'blocks/twitter_block.html'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('shell', 'Shell')], 'label': 'Language code'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Source code'}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {}), 13: ('utils.models.UtilsResultBlock', (), {})}),
        ),
    ]
