# Generated by Django 5.1.2 on 2024-11-07 16:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('reading_time_in_minutes', models.IntegerField()),
                ('body', wagtail.fields.StreamField([('content', 0), ('image', 1), ('quote', 2), ('video_block', 7), ('twitter_block', 9), ('code_block', 12), ('result_block', 13)], block_lookup={0: ('utils.models.UtilsCustomRichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('video_file', 5), ('poster_image', 6)]], {'template': 'blocks/video_block.html'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8)]], {'template': 'blocks/twitter_block.html'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('shell', 'Shell')], 'label': 'Language code'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Source code'}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {}), 13: ('utils.models.UtilsResultBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPageCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='project.projectpage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.utilscategory')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
