# Generated by Django 5.1.2 on 2024-11-07 16:53

import django.db.models.deletion
import experience.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExperiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_in', models.IntegerField(blank=True, null=True, validators=[experience.models.validate_year], verbose_name="Date d'entrée")),
                ('date_out', models.IntegerField(blank=True, null=True, validators=[experience.models.validate_year], verbose_name='Date de sortie')),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('content', 0), ('image', 1), ('quote', 2), ('video_block', 7), ('twitter_block', 9), ('code_block', 12), ('result_block', 13)], block_lookup={0: ('utils.models.UtilsCustomRichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('video_file', 5), ('poster_image', 6)]], {'template': 'blocks/video_block.html'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8)]], {'template': 'blocks/twitter_block.html'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('shell', 'Shell')], 'label': 'Language code'}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Source code'}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {}), 13: ('utils.models.UtilsResultBlock', (), {})})),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
